FROM python:3.9

# Installation de MLflow
RUN pip install mlflow

# Expose le port par défaut pour l'UI de MLflow
EXPOSE 5000

# Commande par défaut pour démarrer MLflow
CMD ["mlflow", "server", "--host", "0.0.0.0", "--backend-store-uri", "file:/mlflow"]
